import Head from "next/head";
import { Inter } from "@next/font/google";
import SideBar from "@/components/SideBar";
import Feed from "@/components/Feed";
import Login from "@/components/Login";
import Modal from "@/components/Modal";
import { getProviders, getSession, useSession } from "next-auth/react";
import { useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ providers }) {
    const { data: session } = useSession();
    const {
        modal: { isModalOpen },
    } = useSelector((state) => state);

    if (!session) return <Login providers={providers} />;

    return (
        <>
            <Head>
                <title>social media app</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
                <SideBar />
                <Feed />
                {isModalOpen && <Modal />}
            </main>
        </>
    );
}

export async function getServerSideProps(context) {
    const providers = await getProviders();
    const session = await getSession(context);
    return {
        props: { providers, session },
    };
}
