import Head from "next/head";
import SideBar from "./SideBar";
import Widget from "./Widget";

const Outline = ({ children }) => {
    return (
        <>
            <Head>
                <title>social media app</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white min-h-screen flex max-w-[1500px] mx-auto">
                <SideBar />
                {children}
                <Widget/>
            </main>
        </>
    );
};

export default Outline;
